# 2. Создание нейронной сети без использования готовых решений

__Автор__: Никита Владимирович Блохин (NVBlokhin@fa.ru)

Финансовый университет, 2020 г. 

In [1]:
import torch

## 1. Создание нейронов и полносвязных слоев

1.1. Используя операции над матрицами и векторами из библиотеки `torch`, реализовать нейрон с заданными весами `weights` и `bias`. Прогнать вектор `inputs` через нейрон и вывести результат. 

In [2]:
class Neuron:

  def __init__(self, weights, bias):
    self.bias = bias
    self.weights = weights
  
  def forward(self, inputs):
    z = self.bias + torch.sum(self.weights * inputs)
    return z


In [3]:
inputs = torch.tensor([1.0, 2.0, 3.0, 4.0])
weights = torch.tensor([-0.2, 0.3, -0.5, 0.7])
bias = 3.14

In [4]:
neuron = Neuron(weights, bias)
out = neuron.forward(inputs)
out

tensor(4.8400)

1.2 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать полносвязный слой с заданными весами `weights` и `biases`. Прогнать вектор `inputs` через слой и вывести результат. 

In [5]:
class Linear:
  biases = torch.tensor([])
  weights = torch.tensor([])

  def __init__(self, weights, bias):
    self.biases = bias
    self.weights = weights
  
  def forward(self, inputs):
    if len(inputs.shape) == 1:
      shaped = inputs.view(inputs.shape[0], 1)
    else:
      shaped = inputs.T
    mp = shaped * weights
    bimp = biases + mp
    su = bimp.sum(dim=1)
    return su

In [6]:
inputs = torch.tensor([1.0, 2.0, 3.0, 4.0])
weights = torch.tensor([[-0.2, 0.3, -0.5, 0.7],
                        [0.5, -0.91, 0.26, -0.5],
                        [-0.26, -0.27, 0.17, 0.87]]).T

biases = torch.tensor([3.14, 2.71, 7.2])

In [7]:
linear = Linear(weights, biases)
out = linear.forward(inputs)
out

tensor([13.0900, 11.2900, 12.8400, 17.3300])

In [112]:
weights

tensor([[-0.2000,  0.5000, -0.2600],
        [ 0.3000, -0.9100, -0.2700],
        [-0.5000,  0.2600,  0.1700],
        [ 0.7000, -0.5000,  0.8700]])

In [127]:
inputs

tensor([[ 1.0000,  2.0000,  3.0000,  2.5000],
        [ 2.0000,  5.0000, -1.0000,  2.0000],
        [-1.5000,  2.7000,  3.3000, -0.8000]])

In [129]:
inputs.T

tensor([[ 1.0000,  2.0000, -1.5000],
        [ 2.0000,  5.0000,  2.7000],
        [ 3.0000, -1.0000,  3.3000],
        [ 2.5000,  2.0000, -0.8000]])

In [145]:
len(inputs.shape)

2

In [139]:
torch.transpose(input, 1, 0)

TypeError: ignored

In [132]:
inputs.T * weights

RuntimeError: ignored

In [124]:
inputs.view(4, 3)

tensor([[ 1.0000,  2.0000,  3.0000],
        [ 2.5000,  2.0000,  5.0000],
        [-1.0000,  2.0000, -1.5000],
        [ 2.7000,  3.3000, -0.8000]])

In [118]:
inputs.view(inputs.shape[0], 1) 

RuntimeError: ignored

In [115]:
mp = inputs.view(inputs.shape[0], 1) * weights
mp

RuntimeError: ignored

In [95]:
bimp = biases + mp
bimp

tensor([[ 2.9400,  3.2100,  6.9400],
        [ 3.7400,  0.8900,  6.6600],
        [ 1.6400,  3.4900,  7.7100],
        [ 5.9400,  0.7100, 10.6800]])

In [96]:
su = bimp.sum(dim=1)
su

tensor([13.0900, 11.2900, 12.8400, 17.3300])

1.3 Реализовать полносвязный слой из __2.1.2__ таким образом, чтобы он мог принимать на вход матрицу (батч) с данными. Продемонстрировать работу.
Результатом прогона сквозь слой должна быть матрица размера `batch_size` x `n_neurons`.


In [8]:
inputs = torch.tensor([[1, 2, 3, 2.5], 
                       [2, 5, -1, 2], 
                       [-1.5, 2.7, 3.3, -0.8]])

In [9]:
out2 = linear.forward(inputs)

In [10]:
out2

tensor([14.2400,  8.3710, 11.8510, 13.1040])

1.4 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать полносвязный слой из `n_neurons` нейронов с `n_features` весами у каждого нейрона (инициализируются из стандартного нормального распределения). Прогнать вектор `inputs` через слой и вывести результат. Результатом прогона сквозь слой должна быть матрица размера `batch_size` x `n_neurons`.

In [ ]:
class Linear:
  def __init__(self, n_features, n_neurons):
    # <создать атрибуты объекта weights и biases>
    pass
  
  def forward(self, inputs):
    return # <реализовать логику слоя>

1.5 Используя решение из __1.4__, создать 2 полносвязных слоя и пропустить матрицу `inputs` последовательно через эти два слоя. Количество нейронов в первом слое выбрать произвольно, количество нейронов во втором слое выбрать так, чтобы результатом прогона являлась матрица (3x7). 

In [ ]:
inputs = torch.tensor([[1, 2, 3, 2.5], 
                       [2, 5, -1, 2], 
                       [-1.5, 2.7, 3.3, -0.8]])