# 01. Знакомство с `torch.Tensor`

---

При решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использование функционала библиотеки `torch`.

[PyTorch documentation](https://pytorch.org/docs/stable/#pytorch-documentation)

In [808]:
import math
import numpy as np
import torch

torch.manual_seed(73)

In [809]:
import sys
sys.version_info

sys.version_info(major=3, minor=10, micro=7, releaselevel='final', serial=0)

## 1.1 Создание тензоров и выполнение базовых операций над ними

[Документация по функциям для создания тензоров](https://pytorch.org/docs/stable/torch.html#creation-ops)

[Документация по функциям для работы с индексами](https://pytorch.org/docs/stable/torch.html#indexing-slicing-joining-mutating-ops)

1.1.1 Создайте двумерный тензор размера (8, 8). Используя как можно меньше операций, добейтесь расстановки кодов "шахматных фигур".

Ожидаемый результат:

```
[[-4., -3., -2., -6., -5., -2., -3., -4.],
 [-1., -1., -1., -1., -1., -1., -1., -1.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [1., 1., 1., 1., 1., 1., 1., 1.],
 [4., 3., 2., 6., 5., 2., 3., 4.]]

```

In [810]:
task1 = torch.zeros((8, 8))
task1

tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])

In [811]:
task1[0] = torch.as_tensor([-4., -3., -2., -6., -5., -2., -3., -4.])
task1[1] = -1
task1[-2] = task1[1] * -1
task1[-1] = task1[0] * -1
task1

tensor([[-4., -3., -2., -6., -5., -2., -3., -4.],
        [-1., -1., -1., -1., -1., -1., -1., -1.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 4.,  3.,  2.,  6.,  5.,  2.,  3.,  4.]])

1.1.2 Средствами `torch` рассчитать произведения четных чисел от 2 до 20 на ближайшие к ним бОльшие нечетные числа.

In [812]:
data = torch.arange(2, 21)
x = data[data % 2 == 0]
y = x + 1
z = x * y
z

tensor([  6,  20,  42,  72, 110, 156, 210, 272, 342, 420])

1.1.3 Создать тензор размера 11x7 вида: [[1, 2, 3, ..., 7], [11, 12, 13, ..., 17], [21, 22, 23, ..., 27], ..., [101, 102, 103, ..., 107]]

In [813]:
x = torch.arange(0, 7)
y = torch.arange(1, 110, 10)
x.unsqueeze(1) + y

tensor([[  1,  11,  21,  31,  41,  51,  61,  71,  81,  91, 101],
        [  2,  12,  22,  32,  42,  52,  62,  72,  82,  92, 102],
        [  3,  13,  23,  33,  43,  53,  63,  73,  83,  93, 103],
        [  4,  14,  24,  34,  44,  54,  64,  74,  84,  94, 104],
        [  5,  15,  25,  35,  45,  55,  65,  75,  85,  95, 105],
        [  6,  16,  26,  36,  46,  56,  66,  76,  86,  96, 106],
        [  7,  17,  27,  37,  47,  57,  67,  77,  87,  97, 107]])

1.1.4 Написать функцию, которая для целых значений `n` и `m` будет возвращать тензор размера `n`x`m`, заполненный текстурой размера 2x2, состоящей из следующих значений:

```
0 1

2 3

```

Пример для n = 4 и m = 5:

```
0 1 0 1 0

2 3 2 3 2

0 1 0 1 0

2 3 2 3 2
```

In [814]:
n = 4
m = 5

In [815]:
base = torch.as_tensor([[0, 1], [2, 3]])
base.repeat(n, m)[:n, :m]

tensor([[0, 1, 0, 1, 0],
        [2, 3, 2, 3, 2],
        [0, 1, 0, 1, 0],
        [2, 3, 2, 3, 2]])

1.1.5 Сгенерировать двумерный тензор `t` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в дипазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида $ax+b$ так, что после нормализации максимальный элемент масива будет равен 1.0, минимальный 0.0

In [816]:
a = torch.randint(0, 21, (4, 7), dtype=float)
a

tensor([[13.,  4., 13.,  8., 16., 15., 18.],
        [ 9.,  1.,  9.,  0., 12., 19., 11.],
        [18., 12.,  5.,  3.,  8.,  4.,  0.],
        [ 8.,  6., 10.,  8.,  9., 11.,  4.]], dtype=torch.float64)

In [817]:
torch.nn.functional.normalize(a, 16)

tensor([[0.7134, 0.2195, 0.7134, 0.4390, 0.8780, 0.8232, 0.9878],
        [0.4737, 0.0526, 0.4737, 0.0000, 0.6315, 0.9999, 0.5789],
        [0.9999, 0.6666, 0.2778, 0.1667, 0.4444, 0.2222, 0.0000],
        [0.7165, 0.5374, 0.8956, 0.7165, 0.8060, 0.9852, 0.3582]],
       dtype=torch.float64)

[Random Sampling](https://pytorch.org/docs/stable/torch.html#random-sampling)

[Distributions](https://pytorch.org/docs/stable/distributions.html)

1.1.6 Задать два двумерных тензора `ar1` и `ar2` размерности (4, 7), состоящих из случайных целых чисел в пределах от 0 до 10. Построить двумерный тензор размерности (4, 7), каждый элемент которого представляет собой максимум из двух значений, находящихся на аналогичной позиции в массивах `ar1`, `ar2`.

[Reductions ops](https://pytorch.org/docs/stable/torch.html#reduction-ops)

In [818]:
ar1 = torch.randint(0, 10, (4, 7))
ar2 = torch.randint(0, 10, (4, 7))
ar1, ar2

(tensor([[1, 7, 3, 3, 1, 8, 3],
         [5, 9, 9, 0, 2, 5, 1],
         [1, 2, 6, 4, 9, 0, 9],
         [5, 6, 3, 6, 6, 3, 1]]),
 tensor([[0, 3, 9, 8, 3, 5, 6],
         [4, 4, 6, 9, 7, 0, 2],
         [9, 2, 4, 7, 5, 1, 4],
         [9, 8, 9, 3, 0, 1, 8]]))

In [819]:
torch.where(ar1>ar2, ar1, ar2)

tensor([[1, 7, 9, 8, 3, 8, 6],
        [5, 9, 9, 9, 7, 5, 2],
        [9, 2, 6, 7, 9, 1, 9],
        [9, 8, 9, 6, 6, 3, 8]])

1.1.7 Создать тензор из 20 случайных целых чисел от 0 до 100. Получить второе сверху значение в тензоре. Определить индекс этого значения.

In [820]:
x = torch.randint(0, 101, (20, ))
values, indices = x.sort()
x

tensor([63, 41,  2, 15, 57, 17, 51, 52, 75, 96, 56, 57, 38, 61, 86, 66, 17, 68,
        41, 81])

In [821]:
x.sort()

torch.return_types.sort(
values=tensor([ 2, 15, 17, 17, 38, 41, 41, 51, 52, 56, 57, 57, 61, 63, 66, 68, 75, 81,
        86, 96]),
indices=tensor([ 2,  3,  5, 16, 12,  1, 18,  6,  7, 10,  4, 11, 13,  0, 15, 17,  8, 19,
        14,  9]))

In [822]:
values[-1], indices[-1]

(tensor(96), tensor(9))

## 1.2 Распространение

[Numpy broadcasting](https://numpy.org/devdocs/user/theory.broadcasting.html)

[Torch broadcasting](https://pytorch.org/docs/stable/notes/broadcasting.html)

1.2.1 Создать тензор 11x7 вида: `[[1, 2, 3, ..., 7], [11, 12, 13, ..., 17], [21, 22, 23, ..., 27], ..., [101, 102, 103, ..., 107]]`. При решении задачи применить технику распространения.

In [823]:
x = torch.arange(0, 7).unsqueeze(1)
y = torch.arange(1, 110, 10)
x, y

(tensor([[0],
         [1],
         [2],
         [3],
         [4],
         [5],
         [6]]),
 tensor([  1,  11,  21,  31,  41,  51,  61,  71,  81,  91, 101]))

In [824]:
x + y

tensor([[  1,  11,  21,  31,  41,  51,  61,  71,  81,  91, 101],
        [  2,  12,  22,  32,  42,  52,  62,  72,  82,  92, 102],
        [  3,  13,  23,  33,  43,  53,  63,  73,  83,  93, 103],
        [  4,  14,  24,  34,  44,  54,  64,  74,  84,  94, 104],
        [  5,  15,  25,  35,  45,  55,  65,  75,  85,  95, 105],
        [  6,  16,  26,  36,  46,  56,  66,  76,  86,  96, 106],
        [  7,  17,  27,  37,  47,  57,  67,  77,  87,  97, 107]])

1.2.2 Вычесть одномерный тензор `b_1d` из двухмерного тензора `a_2d`, так, чтобы каждый элемент одномерного тензора вычитался из всех элементов соответствующих строк двумерного тензора.

_Пример:_

Для входа:
```python
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,2,3])
```

Ожидается резульат:

```python
[[2 2 2]
 [2 2 2]
 [2 2 2]]
```

In [825]:
a_2d = torch.tensor([[3,3,3],[4,4,4],[5,5,5]])
b_1d = torch.tensor([1,2,3])

In [826]:
torch.sub(a_2d, b_1d.unsqueeze(1))

tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])

## 1.3 Индексы, маскирование и прихотливое индексирование

[Документация по функциям для работы с индексами](https://pytorch.org/docs/stable/torch.html#indexing-slicing-joining-mutating-ops)

1.3.1 Получить индексы, для которых элементы тензоров `a` и `b` совпадают.

_Пример:_

Для входа:
```python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

Ожидается резульат:

```python
array([1, 3, 5, 7])
```

In [827]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [828]:
a = torch.tensor(a)
b = torch.tensor(b)
torch.where(a == b)[0]

tensor([1, 3, 5, 7])

1.3.2 Инвертировать порядок элементов в двумерном тензоре `torch.arange(9).view(3,3)`.

Ожидаемый результат:


```python
array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])
```

In [829]:
torch.flip(torch.arange(9).view(3,3), [0, 1])

tensor([[8, 7, 6],
        [5, 4, 3],
        [2, 1, 0]])

1.3.3 Из входного тензора a получить только элементы, находящиеся в диапазоне от 5 до 10.

_Пример:_

Для входа:
```python
a = np.array([2, 6, 1, 9, 10, 3, 27])
```

Ожидается резульат:

```python
array([6, 9, 10])
```

In [830]:
a = torch.tensor([2, 6, 1, 9, 10, 3, 27])
a

tensor([ 2,  6,  1,  9, 10,  3, 27])

In [831]:
a[torch.logical_and(10>=a, 5<=a)]

tensor([ 6,  9, 10])

1.3.4 Поменять местами столбец 1 и 2. тензора `np.arange(9).reshape(3,3)`

In [832]:
a = torch.arange(9).reshape(3,3)
print(a)
torch.index_select(a, 1, torch.LongTensor([1,0,2]))

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


tensor([[1, 0, 2],
        [4, 3, 5],
        [7, 6, 8]])

1.3.5 Создать тензор 8 на 10 из случайных целых чисел из диапазона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [833]:
x = torch.randint(0, 10, (8, 10))
x

tensor([[4, 1, 7, 7, 8, 8, 5, 9, 1, 6],
        [5, 2, 2, 1, 2, 9, 0, 1, 7, 0],
        [7, 0, 9, 6, 2, 2, 9, 6, 9, 1],
        [0, 3, 1, 1, 4, 4, 4, 3, 9, 1],
        [0, 7, 4, 3, 6, 7, 8, 1, 9, 2],
        [4, 4, 4, 6, 8, 7, 7, 9, 5, 5],
        [1, 2, 1, 3, 9, 8, 8, 1, 6, 9],
        [6, 1, 6, 7, 0, 7, 1, 7, 7, 2]])

In [834]:
a = torch.sum(x, 1)
a

tensor([56, 29, 51, 30, 47, 59, 48, 44])

In [835]:
value, ind = torch.min(a, 0)
value, ind

(tensor(29), tensor(1))

In [836]:
ind.item(), x[ind]

(1, tensor([5, 2, 2, 1, 2, 9, 0, 1, 7, 0]))

1.3.6 Cоздать тензор из 20 случайных целых чисел от 0 до 100. Обрезать значения тензора (заменить значения, выходящие за диапазон, на крайние значения) снизу по значению 30, сверху по значению 70.

In [837]:
x = torch.randint(0, 101, (20, ))
x

tensor([77, 10, 79, 22, 95, 23, 73, 70,  9, 83, 76, 52,  9, 51, 56, 48,  5, 97,
        22, 89])

In [838]:
x[x < 30] = 30
x[x > 70] = 70
x

tensor([70, 30, 70, 30, 70, 30, 70, 70, 30, 70, 70, 52, 30, 51, 56, 48, 30, 70,
        30, 70])

1.3.7 Создать два тензора размера 30 на 3 из случайных целых чисел из диапазона от 0 до 10 и найти все значения первого тензора, которые больше соответсвующих (по расположению) значений второго тензора. Подсчитать сумму этих значений.

In [839]:
a = torch.randint(0, 10, (30, 3))
b = torch.randint(0, 10, (30, 3))
a, b

(tensor([[0, 2, 7],
         [1, 5, 4],
         [4, 1, 2],
         [6, 2, 6],
         [2, 7, 4],
         [7, 9, 8],
         [6, 2, 0],
         [8, 4, 8],
         [7, 7, 4],
         [4, 4, 6],
         [1, 0, 9],
         [7, 9, 9],
         [6, 2, 3],
         [0, 3, 3],
         [1, 3, 0],
         [5, 7, 8],
         [4, 6, 4],
         [6, 9, 8],
         [8, 5, 9],
         [9, 7, 1],
         [2, 4, 4],
         [2, 3, 9],
         [0, 6, 3],
         [0, 5, 3],
         [1, 6, 0],
         [3, 6, 8],
         [8, 8, 5],
         [8, 3, 7],
         [6, 8, 2],
         [3, 3, 3]]),
 tensor([[0, 4, 4],
         [8, 2, 4],
         [3, 4, 3],
         [7, 5, 6],
         [3, 8, 9],
         [5, 7, 4],
         [7, 3, 0],
         [3, 1, 8],
         [4, 8, 5],
         [6, 4, 8],
         [8, 2, 9],
         [1, 3, 7],
         [7, 5, 9],
         [6, 4, 2],
         [3, 8, 6],
         [4, 8, 2],
         [8, 2, 0],
         [1, 5, 8],
         [8, 9, 3],
         [3, 1, 7]

In [840]:
a[a > b]

tensor([7, 5, 4, 7, 9, 8, 8, 4, 7, 7, 9, 9, 3, 5, 8, 6, 4, 6, 9, 9, 9, 7, 4, 4,
        9, 6, 6, 8, 8, 8, 5, 8, 7, 6, 8, 3])

In [841]:
a[a > b].sum()

tensor(240)

1.3.8 При помощи прихотливого индексирования для двухмерного массива размерности (20, 20), состоящего из случайных целых чисел в пределах от 0 до 10 получить массив элементов находящихся на диагонали, проходящей над основной диагональю.

In [842]:
x = torch.randint(0, 10, (20, 20))
x

tensor([[0, 6, 6, 0, 8, 4, 0, 7, 9, 4, 0, 0, 7, 7, 1, 6, 4, 1, 5, 8],
        [0, 8, 8, 1, 4, 8, 2, 7, 6, 9, 5, 1, 3, 3, 6, 8, 9, 7, 8, 6],
        [4, 0, 5, 0, 7, 7, 0, 7, 0, 5, 5, 9, 1, 2, 1, 8, 4, 7, 9, 0],
        [9, 6, 9, 0, 2, 6, 5, 4, 3, 6, 6, 8, 9, 1, 9, 7, 8, 6, 0, 7],
        [3, 0, 5, 5, 6, 4, 9, 6, 1, 9, 9, 6, 2, 4, 4, 7, 9, 3, 8, 7],
        [4, 4, 4, 6, 3, 8, 2, 1, 1, 2, 9, 3, 3, 4, 8, 4, 6, 0, 4, 5],
        [4, 4, 5, 9, 5, 5, 5, 6, 7, 7, 0, 9, 3, 3, 5, 3, 0, 1, 9, 8],
        [3, 4, 4, 9, 4, 0, 1, 0, 2, 0, 9, 4, 2, 9, 4, 0, 2, 9, 0, 4],
        [3, 7, 8, 5, 6, 2, 2, 4, 0, 4, 8, 4, 4, 6, 3, 3, 4, 1, 7, 7],
        [5, 4, 1, 7, 6, 7, 5, 0, 8, 1, 7, 4, 5, 7, 7, 1, 7, 2, 9, 6],
        [2, 2, 5, 8, 1, 5, 8, 3, 3, 9, 6, 8, 8, 2, 5, 4, 9, 5, 0, 9],
        [9, 7, 0, 3, 8, 9, 0, 9, 4, 7, 9, 6, 2, 2, 4, 1, 9, 3, 4, 7],
        [1, 1, 7, 7, 0, 4, 9, 5, 3, 6, 6, 3, 3, 4, 9, 3, 2, 8, 5, 5],
        [4, 4, 1, 8, 5, 1, 4, 0, 9, 3, 9, 0, 3, 0, 2, 5, 2, 6, 6, 7],
        [5, 0, 7, 7,

In [843]:
torch.diag(x, 1)

tensor([6, 8, 0, 2, 4, 2, 6, 2, 4, 7, 8, 2, 4, 2, 3, 4, 4, 5, 5])

1.3.9 Задать два двухмерных тензора `ar1` и `ar2` размерности (5, 10), состоящих из случайных целых чисел в пределах от 0 до 10. Удвоить все значения `ar1`, которые совпадают со значениями `ar2`, расположенными на аналогичных позициях.

In [844]:
ar1 = torch.randint(0, 11, (5, 10))
ar2 = torch.randint(0, 11, (5, 10))
ar1, ar2

(tensor([[ 0,  5,  8,  3, 10,  7,  0,  1,  1,  1],
         [ 2,  8,  7, 10,  5,  2,  3,  7,  2,  9],
         [ 1, 10,  2,  6,  9,  5,  1,  8,  8,  3],
         [ 6,  6,  3,  9,  0,  3,  1,  4,  4,  9],
         [ 8,  9,  7,  0,  6,  8, 10,  1, 10, 10]]),
 tensor([[ 3,  4,  0,  9,  3,  6,  8,  3,  3,  0],
         [ 5,  5, 10, 10,  3,  0,  4,  5,  9,  9],
         [ 0,  6,  7,  0,  0,  3,  6,  7,  1,  5],
         [10,  6,  5,  7,  4,  9,  4,  9,  6,  6],
         [ 1,  0, 10,  2,  4,  0,  9,  0, 10,  4]]))

In [845]:
ar1 == ar2

tensor([[False, False, False, False, False, False, False, False, False, False],
        [False, False, False,  True, False, False, False, False, False,  True],
        [False, False, False, False, False, False, False, False, False, False],
        [False,  True, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False,  True, False]])

In [846]:
torch.where(ar1==ar2, ar1**2, ar2)

tensor([[  3,   4,   0,   9,   3,   6,   8,   3,   3,   0],
        [  5,   5,  10, 100,   3,   0,   4,   5,   9,  81],
        [  0,   6,   7,   0,   0,   3,   6,   7,   1,   5],
        [ 10,  36,   5,   7,   4,   9,   4,   9,   6,   6],
        [  1,   0,  10,   2,   4,   0,   9,   0, 100,   4]])

1.3.10 Заданы три двухмерных тензора `ar1`, `ar2` и `ar3` размерности (4, 7), состоящие из случайных целых чисел в пределах от 0 до 10. Обнулить все элементы `ar1`, которые больше соответствующих (находящихся в соответствующих позициях) элементов `ar2` и меньше соответствующих элементов `ar3`.


In [847]:
ar1 = torch.randint(0, 10, (4, 7))
ar2 = torch.randint(0, 10, (4, 7))
ar3 = torch.randint(0, 10, (4, 7))
ar1, ar2, ar3

(tensor([[2, 3, 3, 6, 9, 8, 3],
         [5, 1, 1, 4, 9, 4, 5],
         [6, 2, 7, 4, 7, 8, 2],
         [3, 0, 3, 8, 3, 8, 8]]),
 tensor([[2, 0, 1, 9, 3, 5, 7],
         [6, 8, 9, 0, 0, 4, 4],
         [1, 7, 7, 2, 3, 1, 6],
         [7, 1, 5, 2, 0, 1, 3]]),
 tensor([[9, 4, 6, 4, 2, 4, 0],
         [3, 1, 4, 5, 7, 5, 9],
         [2, 0, 0, 7, 6, 1, 9],
         [2, 7, 7, 8, 6, 8, 0]]))

In [848]:
mask1 = ar1>ar2
mask2 = ar1<ar3

In [849]:
mask1

tensor([[False,  True,  True, False,  True,  True, False],
        [False, False, False,  True,  True, False,  True],
        [ True, False, False,  True,  True,  True, False],
        [False, False, False,  True,  True,  True,  True]])

In [850]:
mask2

tensor([[ True,  True,  True, False, False, False, False],
        [False, False,  True,  True, False,  True,  True],
        [False, False, False,  True, False, False,  True],
        [False,  True,  True, False,  True, False, False]])

In [851]:
mask = mask1 & mask2
mask

tensor([[False,  True,  True, False, False, False, False],
        [False, False, False,  True, False, False,  True],
        [False, False, False,  True, False, False, False],
        [False, False, False, False,  True, False, False]])

In [852]:
ar1[mask] = 0
ar1

tensor([[2, 0, 0, 6, 9, 8, 3],
        [5, 1, 1, 0, 9, 4, 0],
        [6, 2, 7, 0, 7, 8, 2],
        [3, 0, 3, 8, 0, 8, 8]])

1.3.11 Задан двумерный тензор `ar1` размерности (20, 5), состоящий из случайных целых чисел в пределах от 0 до 20. Определить, в каких столбцах не менее 5 раз встречается значение, максимальное по своей строке.

In [853]:
ar1 = torch.randint(0, 20, (20, 5))
ar1

tensor([[18,  4,  3, 19, 11],
        [12, 17, 18, 17, 11],
        [ 1, 15,  4,  3, 16],
        [ 8, 15, 18, 19,  2],
        [18,  8, 17,  9, 14],
        [ 9,  2,  1,  8,  4],
        [ 0, 15, 10,  5, 12],
        [ 8, 13, 12, 14,  3],
        [13, 19, 19, 13,  2],
        [ 4, 18,  9,  7,  2],
        [ 9,  5, 13, 10, 15],
        [15,  8,  9, 12,  0],
        [19, 15, 16,  0, 18],
        [15, 17,  9, 18, 12],
        [ 8, 19, 12, 13,  1],
        [18,  9, 17, 13, 16],
        [10, 18, 18,  5,  4],
        [17, 18,  5,  3,  3],
        [ 4, 15, 19, 12,  3],
        [18,  1,  2,  2,  9]])

In [854]:
torch.max(ar1, 0)

torch.return_types.max(
values=tensor([19, 19, 19, 19, 18]),
indices=tensor([12,  8,  8,  0, 12]))

In [855]:
ar1 == torch.max(ar1, 0).values

tensor([[False, False, False,  True, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False,  True, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False,  True,  True, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [ True, False, False, False,  True],
        [False, False, False, False, False],
        [False,  True, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False,  True, False, False],
        [False, False, False, False, False]])

In [856]:
torch.sum((ar1 == torch.max(ar1, 0).values), 0)

tensor([1, 2, 2, 2, 1])

In [857]:
torch.isin(5, torch.sum((ar1 == torch.max(ar1, 0).values), 0))

tensor(False)

In [858]:
more_then_five = torch.sum((ar1 == torch.max(ar1, 0).values), 0) >= 5
more_then_five

tensor([False, False, False, False, False])

In [859]:
if torch.isin(5, torch.sum((ar1 == torch.max(ar1, 0).values), 0)):
	print("Столбец:", torch.where(more_then_five)[0].item() + 1)
else:
	print("Количество повторяющихся значений меньше 5")

Количество повторяющихся значений меньше 5


1.3.12 Задан двумерный тензор `ar1` размерности (4, 7), состоящий из случайных  чисел в пределах от 0 до 1. Обнулить все значения в массиве, расположенные строго правее и ниже максимального элемента массива.

In [860]:
ar1 = torch.rand(4, 7)
ar1

tensor([[0.6932, 0.0995, 0.3391, 0.5062, 0.3786, 0.4498, 0.3426],
        [0.0042, 0.5031, 0.9655, 0.2548, 0.4115, 0.0020, 0.4201],
        [0.4337, 0.2021, 0.6049, 0.9168, 0.3325, 0.2174, 0.0023],
        [0.7393, 0.8144, 0.4233, 0.0917, 0.1533, 0.0644, 0.5261]])

In [861]:
ar1.max()

tensor(0.9655)

In [862]:
ar1 == ar1.max()

tensor([[False, False, False, False, False, False, False],
        [False, False,  True, False, False, False, False],
        [False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False]])

In [863]:
x, y = torch.where(ar1 == ar1.max())
x, y

(tensor([1]), tensor([2]))

In [864]:
ar1[:x+1, :y+1]

tensor([[0.6932, 0.0995, 0.3391],
        [0.0042, 0.5031, 0.9655]])

1.3.13 Построить \"one-hot encoding\" для одномерного тензора, содержащего целые числа (длина вектора заранее неизвестна, набор значений заранее неизвестен, при этом в итоговой матрице должны присутствовать столбцы для всех натуральных чисел вплоть до максимального встречающегося в исходном массиве).

In [865]:
x = torch.tensor([2, 3, 2, 2, 2, 1])
x

tensor([2, 3, 2, 2, 2, 1])

In [866]:
torch.nn.functional.one_hot(x)[:, 1:]

tensor([[0, 1, 0],
        [0, 0, 1],
        [0, 1, 0],
        [0, 1, 0],
        [0, 1, 0],
        [1, 0, 0]])

1.3.14 Создать тензор `arr` из 20 случайных целых чисел от 0 до 100. Найти самое частое значение в тензоре. 
Найти индексы в тензоре, соответствующие самому частому значению. Проверить, как работет алгоритм при двух значениях, имеющих наибольшую встречаемость, предложить приемлемое поведение алгоритма для этого случая.

In [867]:
arr = torch.randint(0, 100, (20, ))
arr

tensor([99, 45, 35, 16, 78, 85, 18, 20, 79, 70, 67, 79, 29, 16, 62, 74, 37, 14,
        50,  8])

In [868]:
bc = torch.bincount(arr)
bc

tensor([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 2, 0, 1, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
        0, 0, 1, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1])

In [869]:
ind = torch.where(bc == bc.max(0)[0])[0]
ind

tensor([16, 79])

In [870]:
torch.isin(arr, ind)

tensor([False, False, False,  True, False, False, False, False,  True, False,
        False,  True, False,  True, False, False, False, False, False, False])

In [871]:
print("Индексы: ", torch.where(torch.isin(arr, ind))[0].tolist())

Индексы:  [3, 8, 11, 13]


## 1.4 Математические задачи

1.4.1 Приблизительно (с погрешностью порядка 1%) рассчитать на какой части интервала от 0 до 10 значение функции x * sin(x) больше 0.5.

In [872]:
x = torch.arange(0, 10, 0.1)
x

tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000, 1.0000, 1.1000, 1.2000, 1.3000, 1.4000, 1.5000, 1.6000, 1.7000,
        1.8000, 1.9000, 2.0000, 2.1000, 2.2000, 2.3000, 2.4000, 2.5000, 2.6000,
        2.7000, 2.8000, 2.9000, 3.0000, 3.1000, 3.2000, 3.3000, 3.4000, 3.5000,
        3.6000, 3.7000, 3.8000, 3.9000, 4.0000, 4.1000, 4.2000, 4.3000, 4.4000,
        4.5000, 4.6000, 4.7000, 4.8000, 4.9000, 5.0000, 5.1000, 5.2000, 5.3000,
        5.4000, 5.5000, 5.6000, 5.7000, 5.8000, 5.9000, 6.0000, 6.1000, 6.2000,
        6.3000, 6.4000, 6.5000, 6.6000, 6.7000, 6.8000, 6.9000, 7.0000, 7.1000,
        7.2000, 7.3000, 7.4000, 7.5000, 7.6000, 7.7000, 7.8000, 7.9000, 8.0000,
        8.1000, 8.2000, 8.3000, 8.4000, 8.5000, 8.6000, 8.7000, 8.8000, 8.9000,
        9.0000, 9.1000, 9.2000, 9.3000, 9.4000, 9.5000, 9.6000, 9.7000, 9.8000,
        9.9000])

In [873]:
z = x * torch.sin(x)
z

tensor([ 0.0000,  0.0100,  0.0397,  0.0887,  0.1558,  0.2397,  0.3388,  0.4510,
         0.5739,  0.7050,  0.8415,  0.9803,  1.1184,  1.2526,  1.3796,  1.4962,
         1.5993,  1.6858,  1.7529,  1.7980,  1.8186,  1.8127,  1.7787,  1.7151,
         1.6211,  1.4962,  1.3403,  1.1539,  0.9380,  0.6938,  0.4234,  0.1289,
        -0.1868, -0.5206, -0.8688, -1.2277, -1.5931, -1.9604, -2.3251, -2.6823,
        -3.0272, -3.3549, -3.6606, -3.9395, -4.1870, -4.3989, -4.5710, -4.6996,
        -4.7816, -4.8140, -4.7946, -4.7217, -4.5940, -4.4110, -4.1729, -3.8805,
        -3.5351, -3.1389, -2.6947, -2.2059, -1.6765, -1.1112, -0.5152,  0.1059,
         0.7459,  1.3983,  2.0562,  2.7125,  3.3600,  3.9912,  4.5989,  5.1757,
         5.7144,  6.2082,  6.6504,  7.0350,  7.3562,  7.6089,  7.7886,  7.8916,
         7.9149,  7.8561,  7.7140,  7.4880,  7.1786,  6.7871,  6.3158,  5.7678,
         5.1473,  4.4591,  3.7091,  2.9038,  2.0506,  1.1574,  0.2329, -0.7139,
        -1.6735, -2.6361, -3.5915, -4.52

In [874]:
z.shape[0]

100

In [875]:
torch.where(z > 0.5)[0]

tensor([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
        26, 27, 28, 29, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
        78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93])

In [876]:
print(f"{torch.where(z > 0.5)[0].shape[0] / z.shape[0] * 100}%")

52.0%


1.4.2 Найти все простые числа в пределах ста. (Для решения предлагается использовать Решето Эратосфена) Использовать не более 1 цикла (желательно).

In [877]:
n = 101
numbers = torch.arange(2, n)
numbers

tensor([  2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,
         16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,
         30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,
         44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,
         58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,
         72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,
         86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99,
        100])

In [878]:
prime = []
for i in range(0, int((n-1) / 4)):
	prime.append(numbers[i].item())
	numbers = numbers[(torch.isin(numbers / numbers[i], numbers, invert=True))]

prime

[2,
 3,
 5,
 7,
 11,
 13,
 17,
 19,
 23,
 29,
 31,
 37,
 41,
 43,
 47,
 53,
 59,
 61,
 67,
 71,
 73,
 79,
 83,
 89,
 97]

1.4.3 Найти евклидово расстояние между двумя одномерными тензорами одинаковой размерности, не используя готовые решения из библиотек.

1.4.4 Создать двумерный тензор 20 на 3, содержащий случайные целые числа от 0 до 100.
Интерпретируя тензор как 20 векторов из 3х компонент, отсортировать его по длине векторов.

In [879]:
x = torch.randint(0, 101, (20, 3), dtype=float)
x

tensor([[  3.,  77.,  94.],
        [ 93.,  27.,  14.],
        [  6.,  99.,  57.],
        [ 30., 100.,  72.],
        [ 68.,  35.,  91.],
        [ 29.,  71.,  21.],
        [ 12.,  37.,  61.],
        [ 21.,  84.,  50.],
        [  5.,  10.,  86.],
        [ 85.,  76.,  11.],
        [ 76.,  84.,  12.],
        [ 64.,  96.,  31.],
        [ 33.,  70.,  47.],
        [  2.,  43.,  26.],
        [ 76.,  74.,  93.],
        [ 22.,  63.,  99.],
        [ 86.,  61.,  48.],
        [ 56.,   7.,  37.],
        [ 60.,  62.,  85.],
        [ 68.,  98.,   7.]], dtype=torch.float64)

In [880]:
x.norm(dim=1, p=2).squeeze(-1)

tensor([121.5483,  97.8468, 114.3941, 126.8227, 118.8697,  79.5173,  72.3464,
         99.9850,  86.7237, 114.5513, 113.9122, 119.4697,  90.5428,  50.2892,
        141.0709, 119.3901, 115.8490,  67.4833, 121.1156, 119.4864],
       dtype=torch.float64)

In [881]:
torch.argsort(x, dim=1)

tensor([[0, 1, 2],
        [2, 1, 0],
        [0, 2, 1],
        [0, 2, 1],
        [1, 0, 2],
        [2, 0, 1],
        [0, 1, 2],
        [0, 2, 1],
        [0, 1, 2],
        [2, 1, 0],
        [2, 0, 1],
        [2, 0, 1],
        [0, 2, 1],
        [0, 2, 1],
        [1, 0, 2],
        [0, 1, 2],
        [2, 1, 0],
        [1, 2, 0],
        [0, 1, 2],
        [2, 0, 1]])

1.4.5 Найти "локальные максимумы" в одномерном тензоре (т.е. значения, большие предыдущего и последующего) `torch.tensor([1, 3, 7, 1, 2, 6, 0, 1])` и вывести их индексы.

1.4.6 Задан произвольный массив numpy (например массив из 100 случайных числе от 0 до 1). Необходимо найти в нем число наиболее близкое к заданному.

1.4.7 Решить матричное уравнение `A*X*B=-C` - найти матрицу X. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [882]:
A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]
B = [[3, -1], [2, 1]]
C = [[7, 21], [11, 8], [8, 4]]

1.4.8 Проверить, является ли система векторов a1 = (3; −3; 0; 7),
a2 = (2; 2; 4; 7), a3 = (1; 2; 3; 4), a4 = (5; −4; 1; 3) линейно зависимой?

1.4.9 Сгенирировать тензор из 200 случайных целых чисел, нормально распрделенных cо стандартным отклонением $\sigma = 10$ и матожиданием $\mu = 0$. Построить тензор гистограммы с 20 бинами. 