# 01. Знакомство с `torch.Tensor`

---

При решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использование функционала библиотеки `torch`.

[PyTorch documentation](https://pytorch.org/docs/stable/#pytorch-documentation)

In [48]:
import numpy as np
import torch

In [49]:
import sys
sys.version_info

sys.version_info(major=3, minor=10, micro=7, releaselevel='final', serial=0)

## 1.1 Создание тензоров и выполнение базовых операций над ними

[Документация по функциям для создания тензоров](https://pytorch.org/docs/stable/torch.html#creation-ops)

[Документация по функциям для работы с индексами](https://pytorch.org/docs/stable/torch.html#indexing-slicing-joining-mutating-ops)

1.1.1 Создайте двумерный тензор размера (8, 8). Используя как можно меньше операций, добейтесь расстановки кодов "шахматных фигур".

Ожидаемый результат:

```
[[-4., -3., -2., -6., -5., -2., -3., -4.],
 [-1., -1., -1., -1., -1., -1., -1., -1.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [1., 1., 1., 1., 1., 1., 1., 1.],
 [4., 3., 2., 6., 5., 2., 3., 4.]]

```

In [50]:
task1 = torch.zeros((8, 8))
task1

tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])

In [51]:
task1[0] = torch.as_tensor([-4., -3., -2., -6., -5., -2., -3., -4.])
task1[1] = -1
task1[-2] = task1[1] * -1
task1[-1] = task1[0] * -1
task1

tensor([[-4., -3., -2., -6., -5., -2., -3., -4.],
        [-1., -1., -1., -1., -1., -1., -1., -1.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 4.,  3.,  2.,  6.,  5.,  2.,  3.,  4.]])

1.1.2 Средствами `torch` рассчитать произведения четных чисел от 2 до 20 на ближайшие к ним бОльшие нечетные числа.

In [52]:
data = torch.arange(2, 21)
x = data[data % 2 == 0]
y = x + 1
z = x * y
z

tensor([  6,  20,  42,  72, 110, 156, 210, 272, 342, 420])

1.1.3 Создать тензор размера 11x7 вида: [[1, 2, 3, ..., 7], [11, 12, 13, ..., 17], [21, 22, 23, ..., 27], ..., [101, 102, 103, ..., 107]]

In [53]:
x = torch.arange(0, 7)
y = torch.arange(1, 110, 10)
x.unsqueeze(1) + y

tensor([[  1,  11,  21,  31,  41,  51,  61,  71,  81,  91, 101],
        [  2,  12,  22,  32,  42,  52,  62,  72,  82,  92, 102],
        [  3,  13,  23,  33,  43,  53,  63,  73,  83,  93, 103],
        [  4,  14,  24,  34,  44,  54,  64,  74,  84,  94, 104],
        [  5,  15,  25,  35,  45,  55,  65,  75,  85,  95, 105],
        [  6,  16,  26,  36,  46,  56,  66,  76,  86,  96, 106],
        [  7,  17,  27,  37,  47,  57,  67,  77,  87,  97, 107]])

1.1.4 Написать функцию, которая для целых значений `n` и `m` будет возвращать тензор размера `n`x`m`, заполненный текстурой размера 2x2, состоящей из следующих значений:

```
0 1

2 3

```

Пример для n = 4 и m = 5:

```
0 1 0 1 0

2 3 2 3 2

0 1 0 1 0

2 3 2 3 2
```

In [54]:
n = 4
m = 5

In [55]:
base = torch.as_tensor([[0, 1], [2, 3]])
base.repeat(n, m)[:n, :m]

tensor([[0, 1, 0, 1, 0],
        [2, 3, 2, 3, 2],
        [0, 1, 0, 1, 0],
        [2, 3, 2, 3, 2]])

1.1.5 Сгенерировать двумерный тензор `t` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в дипазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида $ax+b$ так, что после нормализации максимальный элемент масива будет равен 1.0, минимальный 0.0

In [56]:
a = torch.randint(0, 21, (4, 7), dtype=float)
a

tensor([[18.,  1., 13.,  0., 19.,  5., 12.],
        [18.,  9., 12.,  6.,  9., 15.,  9.],
        [13.,  5.,  1.,  8.,  6., 17., 10.],
        [18., 15.,  9.,  8.,  4.,  9., 15.]], dtype=torch.float64)

In [57]:
torch.nn.functional.normalize(a, 16)

tensor([[0.9267, 0.0515, 0.6693, 0.0000, 0.9782, 0.2574, 0.6178],
        [0.9966, 0.4983, 0.6644, 0.3322, 0.4983, 0.8305, 0.4983],
        [0.7640, 0.2939, 0.0588, 0.4702, 0.3526, 0.9991, 0.5877],
        [0.9936, 0.8280, 0.4968, 0.4416, 0.2208, 0.4968, 0.8280]],
       dtype=torch.float64)

[Random Sampling](https://pytorch.org/docs/stable/torch.html#random-sampling)

[Distributions](https://pytorch.org/docs/stable/distributions.html)

1.1.6 Задать два двумерных тензора `ar1` и `ar2` размерности (4, 7), состоящих из случайных целых чисел в пределах от 0 до 10. Построить двумерный тензор размерности (4, 7), каждый элемент которого представляет собой максимум из двух значений, находящихся на аналогичной позиции в массивах `ar1`, `ar2`.

[Reductions ops](https://pytorch.org/docs/stable/torch.html#reduction-ops)

In [58]:
ar1 = torch.randint(0, 10, (4, 7))
ar2 = torch.randint(0, 10, (4, 7))
ar1, ar2

(tensor([[5, 0, 1, 4, 7, 7, 1],
         [0, 8, 5, 2, 4, 8, 9],
         [4, 1, 8, 2, 9, 5, 6],
         [4, 8, 5, 0, 4, 8, 4]]),
 tensor([[4, 6, 8, 2, 5, 0, 8],
         [6, 2, 7, 7, 2, 2, 0],
         [2, 2, 2, 5, 4, 1, 5],
         [2, 5, 8, 2, 5, 7, 4]]))

In [59]:
torch.where(ar1>ar2, ar1, ar2)

tensor([[5, 6, 8, 4, 7, 7, 8],
        [6, 8, 7, 7, 4, 8, 9],
        [4, 2, 8, 5, 9, 5, 6],
        [4, 8, 8, 2, 5, 8, 4]])

1.1.7 Создать тензор из 20 случайных целых чисел от 0 до 100. Получить второе сверху значение в тензоре. Определить индекс этого значения.

In [60]:
x = torch.randint(0, 101, (20, ))
values, indices = x.sort()
x

tensor([36, 33, 93, 58, 18, 86, 65, 60, 65,  5, 30, 53, 68, 61, 38, 11, 17, 52,
        49, 80])

In [61]:
x.sort()

torch.return_types.sort(
values=tensor([ 5, 11, 17, 18, 30, 33, 36, 38, 49, 52, 53, 58, 60, 61, 65, 65, 68, 80,
        86, 93]),
indices=tensor([ 9, 15, 16,  4, 10,  1,  0, 14, 18, 17, 11,  3,  7, 13,  6,  8, 12, 19,
         5,  2]))

In [62]:
values[-1], indices[-1]

(tensor(93), tensor(2))

## 1.2 Распространение

[Numpy broadcasting](https://numpy.org/devdocs/user/theory.broadcasting.html)

[Torch broadcasting](https://pytorch.org/docs/stable/notes/broadcasting.html)

1.2.1 Создать тензор 11x7 вида: `[[1, 2, 3, ..., 7], [11, 12, 13, ..., 17], [21, 22, 23, ..., 27], ..., [101, 102, 103, ..., 107]]`. При решении задачи применить технику распространения.

In [165]:
x = torch.arange(0, 7).unsqueeze(1)
y = torch.arange(1, 110, 10)
x, y

(tensor([[0],
         [1],
         [2],
         [3],
         [4],
         [5],
         [6]]),
 tensor([  1,  11,  21,  31,  41,  51,  61,  71,  81,  91, 101]))

In [166]:
x + y

tensor([[  1,  11,  21,  31,  41,  51,  61,  71,  81,  91, 101],
        [  2,  12,  22,  32,  42,  52,  62,  72,  82,  92, 102],
        [  3,  13,  23,  33,  43,  53,  63,  73,  83,  93, 103],
        [  4,  14,  24,  34,  44,  54,  64,  74,  84,  94, 104],
        [  5,  15,  25,  35,  45,  55,  65,  75,  85,  95, 105],
        [  6,  16,  26,  36,  46,  56,  66,  76,  86,  96, 106],
        [  7,  17,  27,  37,  47,  57,  67,  77,  87,  97, 107]])

1.2.2 Вычесть одномерный тензор `b_1d` из двухмерного тензора `a_2d`, так, чтобы каждый элемент одномерного тензора вычитался из всех элементов соответствующих строк двумерного тензора.

_Пример:_

Для входа:
```python
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,2,3])
```

Ожидается резульат:

```python
[[2 2 2]
 [2 2 2]
 [2 2 2]]
```

In [167]:
a_2d = torch.tensor([[3,3,3],[4,4,4],[5,5,5]])
b_1d = torch.tensor([1,2,3])

In [176]:
torch.sub(a_2d, b_1d.unsqueeze(1))

tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])

## 1.3 Индексы, маскирование и прихотливое индексирование

[Документация по функциям для работы с индексами](https://pytorch.org/docs/stable/torch.html#indexing-slicing-joining-mutating-ops)

1.3.1 Получить индексы, для которых элементы тензоров `a` и `b` совпадают.

_Пример:_

Для входа:
```python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

Ожидается резульат:

```python
array([1, 3, 5, 7])
```

In [63]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [64]:
a = torch.tensor(a)
b = torch.tensor(b)
torch.where(a == b)[0]

tensor([1, 3, 5, 7])

1.3.2 Инвертировать порядок элементов в двумерном тензоре `torch.arange(9).view(3,3)`.

Ожидаемый результат:


```python
array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])
```

In [65]:
torch.flip(torch.arange(9).view(3,3), [0, 1])

tensor([[8, 7, 6],
        [5, 4, 3],
        [2, 1, 0]])

1.3.3 Из входного тензора a получить только элементы, находящиеся в диапазоне от 5 до 10.

_Пример:_

Для входа:
```python
a = np.array([2, 6, 1, 9, 10, 3, 27])
```

Ожидается резульат:

```python
array([6, 9, 10])
```

In [66]:
a = torch.tensor([2, 6, 1, 9, 10, 3, 27])
a

tensor([ 2,  6,  1,  9, 10,  3, 27])

In [67]:
a[torch.logical_and(10>=a, 5<=a)]

tensor([ 6,  9, 10])

1.3.4 Поменять местами столбец 1 и 2. тензора `np.arange(9).reshape(3,3)`

In [68]:
a = torch.arange(9).reshape(3,3)
print(a)
torch.index_select(a, 1, torch.LongTensor([1,0,2]))

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


tensor([[1, 0, 2],
        [4, 3, 5],
        [7, 6, 8]])

1.3.5 Создать тензор 8 на 10 из случайных целых чисел из диапазона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [69]:
x = torch.randint(0, 10, (8, 10))
x

tensor([[9, 7, 1, 9, 9, 1, 5, 7, 2, 1],
        [9, 5, 3, 0, 1, 1, 3, 0, 0, 4],
        [2, 4, 6, 3, 5, 9, 6, 8, 7, 4],
        [7, 8, 9, 3, 3, 1, 4, 7, 4, 1],
        [1, 6, 9, 4, 3, 9, 6, 9, 5, 2],
        [8, 3, 0, 7, 3, 8, 3, 4, 9, 1],
        [7, 0, 6, 2, 6, 1, 8, 6, 9, 2],
        [6, 1, 2, 4, 2, 3, 9, 7, 0, 6]])

In [70]:
a = torch.sum(x, 1)
a

tensor([51, 26, 54, 47, 54, 46, 47, 40])

In [71]:
value, ind = torch.min(a, 0)
value, ind

(tensor(26), tensor(1))

In [72]:
ind.item(), x[ind]

(1, tensor([9, 5, 3, 0, 1, 1, 3, 0, 0, 4]))

1.3.6 Cоздать тензор из 20 случайных целых чисел от 0 до 100. Обрезать значения тензора (заменить значения, выходящие за диапазон, на крайние значения) снизу по значению 30, сверху по значению 70.

In [73]:
x = torch.randint(0, 101, (20, ))
x

tensor([31, 62, 38, 29, 17, 85, 59, 78, 82, 66, 50, 45, 67, 81, 67, 65, 86, 80,
        54, 12])

In [74]:
x[x < 30] = 30
x[x > 70] = 70
x

tensor([31, 62, 38, 30, 30, 70, 59, 70, 70, 66, 50, 45, 67, 70, 67, 65, 70, 70,
        54, 30])

1.3.7 Создать два тензора размера 30 на 3 из случайных целых чисел из диапазона от 0 до 10 и найти все значения первого тензора, которые больше соответсвующих (по расположению) значений второго тензора. Подсчитать сумму этих значений.

In [75]:
a = torch.randint(0, 10, (30, 3))
b = torch.randint(0, 10, (30, 3))
a, b

(tensor([[8, 6, 9],
         [8, 6, 3],
         [2, 8, 8],
         [3, 9, 2],
         [8, 3, 6],
         [2, 5, 2],
         [4, 9, 8],
         [3, 5, 0],
         [0, 5, 7],
         [5, 6, 7],
         [9, 3, 4],
         [8, 9, 5],
         [9, 4, 9],
         [7, 9, 1],
         [9, 0, 2],
         [7, 9, 5],
         [6, 9, 0],
         [1, 4, 0],
         [8, 1, 4],
         [1, 4, 1],
         [3, 1, 6],
         [8, 7, 4],
         [8, 3, 6],
         [3, 5, 8],
         [5, 7, 7],
         [5, 2, 6],
         [3, 1, 4],
         [7, 5, 6],
         [9, 4, 3],
         [9, 3, 3]]),
 tensor([[5, 6, 6],
         [8, 4, 7],
         [8, 0, 0],
         [2, 5, 5],
         [3, 4, 9],
         [4, 6, 3],
         [8, 7, 1],
         [9, 6, 2],
         [2, 9, 5],
         [0, 0, 1],
         [1, 2, 0],
         [4, 1, 5],
         [4, 9, 2],
         [4, 0, 1],
         [9, 9, 0],
         [8, 1, 0],
         [2, 4, 5],
         [0, 1, 4],
         [8, 7, 4],
         [2, 1, 8]

In [76]:
a[a > b]

tensor([8, 9, 6, 8, 8, 3, 9, 8, 9, 8, 7, 5, 6, 7, 9, 3, 4, 8, 9, 9, 9, 7, 9, 2,
        9, 5, 6, 9, 1, 4, 4, 3, 8, 8, 3, 5, 8, 7, 7, 9, 9])

In [77]:
a[a > b].sum()

tensor(275)

1.3.8 При помощи прихотливого индексирования для двухмерного массива размерности (20, 20), состоящего из случайных целых чисел в пределах от 0 до 10 получить массив элементов находящихся на диагонали, проходящей над основной диагональю.

In [78]:
x = torch.randint(0, 10, (20, 20))
x

tensor([[4, 7, 9, 1, 2, 7, 0, 2, 4, 7, 1, 9, 9, 4, 3, 8, 8, 3, 7, 3],
        [7, 1, 8, 3, 1, 8, 1, 9, 0, 4, 1, 2, 5, 1, 7, 9, 7, 8, 5, 5],
        [4, 8, 2, 6, 6, 5, 1, 4, 4, 5, 8, 2, 0, 7, 3, 4, 6, 7, 5, 5],
        [9, 6, 0, 0, 2, 4, 8, 2, 5, 4, 1, 0, 8, 1, 5, 7, 1, 2, 8, 2],
        [1, 5, 7, 3, 3, 4, 1, 9, 6, 2, 8, 3, 8, 1, 4, 4, 3, 5, 4, 4],
        [9, 0, 3, 7, 3, 5, 8, 6, 4, 4, 1, 1, 8, 4, 1, 6, 4, 6, 2, 9],
        [0, 1, 3, 1, 4, 1, 4, 0, 1, 8, 3, 0, 1, 4, 4, 0, 5, 5, 1, 2],
        [3, 2, 7, 0, 1, 3, 2, 8, 0, 4, 4, 7, 7, 8, 6, 9, 3, 7, 7, 0],
        [7, 4, 7, 2, 4, 7, 8, 3, 1, 4, 3, 8, 0, 8, 5, 9, 7, 9, 5, 8],
        [7, 2, 7, 5, 5, 3, 2, 6, 2, 1, 1, 4, 9, 7, 5, 4, 3, 4, 0, 2],
        [8, 4, 5, 1, 3, 1, 3, 7, 0, 3, 0, 3, 2, 2, 1, 4, 4, 7, 0, 4],
        [8, 6, 6, 0, 7, 2, 4, 4, 6, 5, 7, 3, 7, 3, 0, 3, 5, 1, 0, 8],
        [7, 4, 1, 9, 1, 5, 1, 9, 0, 3, 7, 8, 8, 7, 2, 7, 1, 1, 5, 8],
        [1, 6, 0, 8, 0, 9, 6, 3, 9, 2, 5, 1, 8, 0, 4, 1, 6, 7, 8, 2],
        [9, 0, 2, 4,

In [79]:
torch.diag(x, 1)

tensor([7, 8, 6, 2, 4, 8, 0, 0, 4, 1, 3, 7, 7, 4, 8, 3, 0, 9, 9])

1.3.9 Задать два двухмерных тензора `ar1` и `ar2` размерности (5, 10), состоящих из случайных целых чисел в пределах от 0 до 10. Удвоить все значения `ar1`, которые совпадают со значениями `ar2`, расположенными на аналогичных позициях.

In [80]:
ar1 = torch.randint(0, 11, (5, 10))
ar2 = torch.randint(0, 11, (5, 10))
ar1, ar2

(tensor([[ 2,  9,  4,  0,  0,  7, 10,  3,  2,  9],
         [ 2,  9,  1,  6,  2,  9,  8,  6,  1,  4],
         [ 2,  5,  5, 10,  5,  8,  7,  3,  9,  1],
         [ 4,  8,  0,  7,  9,  4, 10,  1,  0, 10],
         [ 6,  9,  4,  6,  3,  0,  0,  6,  3,  1]]),
 tensor([[ 9,  4, 10,  4,  4,  3,  5,  6,  1,  1],
         [10,  1,  2,  5,  0,  3,  0,  2,  3, 10],
         [10,  0,  2,  4,  0, 10,  4,  1,  6,  7],
         [ 9,  5, 10, 10,  6,  7,  7,  7,  5, 10],
         [ 6,  7,  2,  9,  5,  0,  6,  7,  9,  0]]))

In [81]:
ar1 == ar2

tensor([[False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False,  True],
        [ True, False, False, False, False,  True, False, False, False, False]])

In [82]:
torch.where(ar1==ar2, ar1**2, ar2)

tensor([[  9,   4,  10,   4,   4,   3,   5,   6,   1,   1],
        [ 10,   1,   2,   5,   0,   3,   0,   2,   3,  10],
        [ 10,   0,   2,   4,   0,  10,   4,   1,   6,   7],
        [  9,   5,  10,  10,   6,   7,   7,   7,   5, 100],
        [ 36,   7,   2,   9,   5,   0,   6,   7,   9,   0]])

1.3.10 Заданы три двухмерных тензора `ar1`, `ar2` и `ar3` размерности (4, 7), состоящие из случайных целых чисел в пределах от 0 до 10. Обнулить все элементы `ar1`, которые больше соответствующих (находящихся в соответствующих позициях) элементов `ar2` и меньше соответствующих элементов `ar3`.


In [83]:
ar1 = torch.randint(0, 10, (4, 7))
ar2 = torch.randint(0, 10, (4, 7))
ar3 = torch.randint(0, 10, (4, 7))
ar1, ar2, ar3

(tensor([[9, 0, 6, 8, 9, 3, 6],
         [3, 4, 4, 2, 7, 5, 4],
         [3, 4, 3, 0, 2, 8, 6],
         [9, 8, 3, 0, 4, 1, 3]]),
 tensor([[7, 0, 0, 4, 8, 4, 5],
         [9, 6, 7, 3, 9, 2, 0],
         [4, 3, 5, 8, 9, 2, 3],
         [6, 8, 9, 8, 0, 1, 8]]),
 tensor([[1, 8, 6, 2, 1, 8, 6],
         [8, 7, 6, 3, 7, 2, 4],
         [1, 8, 2, 6, 6, 4, 4],
         [0, 6, 4, 7, 9, 7, 8]]))

In [84]:
mask1 = ar1>ar2
mask2 = ar1<ar3

In [85]:
mask1

tensor([[ True, False,  True,  True,  True, False,  True],
        [False, False, False, False, False,  True,  True],
        [False,  True, False, False, False,  True,  True],
        [ True, False, False, False,  True, False, False]])

In [86]:
mask2

tensor([[False,  True, False, False, False,  True, False],
        [ True,  True,  True,  True, False, False, False],
        [False,  True, False,  True,  True, False, False],
        [False, False,  True,  True,  True,  True,  True]])

In [87]:
mask = mask1 & mask2
mask

tensor([[False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False],
        [False,  True, False, False, False, False, False],
        [False, False, False, False,  True, False, False]])

In [88]:
ar1[mask] = 0
ar1

tensor([[9, 0, 6, 8, 9, 3, 6],
        [3, 4, 4, 2, 7, 5, 4],
        [3, 0, 3, 0, 2, 8, 6],
        [9, 8, 3, 0, 0, 1, 3]])

1.3.11 Задан двумерный тензор `ar1` размерности (20, 5), состоящий из случайных целых чисел в пределах от 0 до 20. Определить, в каких столбцах не менее 5 раз встречается значение, максимальное по своей строке.

In [129]:
ar1 = torch.randint(0, 20, (20, 5))
ar1

tensor([[15,  3,  4, 18,  1],
        [10, 15,  5, 14,  1],
        [14, 15,  8,  9, 17],
        [ 6,  5, 16,  7,  6],
        [19, 19,  0,  8,  1],
        [ 5, 14,  2, 12, 17],
        [ 5, 13, 18,  9,  3],
        [19,  8, 12,  5, 12],
        [ 8,  2,  4,  5,  4],
        [19, 17, 19,  9, 15],
        [18,  3,  4,  8,  4],
        [13, 10,  6, 11, 15],
        [15,  1,  9,  8,  3],
        [11,  0,  2,  9,  7],
        [ 4,  1, 17, 10,  1],
        [19, 19,  2,  1, 12],
        [ 2, 10,  9,  0,  3],
        [17, 16, 19,  2, 18],
        [18,  5,  1,  1, 18],
        [19, 17,  2,  3, 12]])

In [130]:
torch.max(ar1, 0)

torch.return_types.max(
values=tensor([19, 19, 19, 18, 18]),
indices=tensor([ 4,  4,  9,  0, 17]))

In [131]:
ar1 == torch.max(ar1, 0).values

tensor([[False, False, False,  True, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [ True,  True, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [ True, False, False, False, False],
        [False, False, False, False, False],
        [ True, False,  True, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [ True,  True, False, False, False],
        [False, False, False, False, False],
        [False, False,  True, False,  True],
        [False, False, False, False,  True],
        [ True, False, False, False, False]])

In [132]:
torch.sum((ar1 == torch.max(ar1, 0).values), 0)

tensor([5, 2, 2, 1, 2])

In [133]:
more_then_five = torch.sum((ar1 == torch.max(ar1, 0).values), 0) >= 5
more_then_five

tensor([ True, False, False, False, False])

In [137]:
if (torch.where(more_then_five)):
	print("Столбец:", torch.where(more_then_five)[0].item() + 1)

Столбец: 1


1.3.12 Задан двумерный тензор `ar1` размерности (4, 7), состоящий из случайных  чисел в пределах от 0 до 1. Обнулить все значения в массиве, расположенные строго правее и ниже максимального элемента массива.

In [138]:
ar1 = torch.rand(4, 7)
ar1

tensor([[0.4691, 0.7525, 0.6495, 0.1111, 0.4301, 0.5324, 0.4167],
        [0.8080, 0.5486, 0.6487, 0.1700, 0.0556, 0.5735, 0.3903],
        [0.5466, 0.2514, 0.4503, 0.7269, 0.4657, 0.6812, 0.6093],
        [0.8660, 0.4724, 0.0222, 0.1272, 0.3376, 0.6325, 0.4012]])

In [139]:
ar1.max()

tensor(0.8660)

In [140]:
ar1 == ar1.max()

tensor([[False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False],
        [ True, False, False, False, False, False, False]])

In [141]:
x, y = torch.where(ar1 == ar1.max())
x, y

(tensor([3]), tensor([0]))

In [142]:
ar1[:x+1, :y+1]

tensor([[0.4691],
        [0.8080],
        [0.5466],
        [0.8660]])

1.3.13 Построить \"one-hot encoding\" для одномерного тензора, содержащего целые числа (длина вектора заранее неизвестна, набор значений заранее неизвестен, при этом в итоговой матрице должны присутствовать столбцы для всех натуральных чисел вплоть до максимального встречающегося в исходном массиве).

In [143]:
x = torch.tensor([2, 3, 2, 2, 2, 1])
x

tensor([2, 3, 2, 2, 2, 1])

In [144]:
torch.nn.functional.one_hot(x)[:, 1:]

tensor([[0, 1, 0],
        [0, 0, 1],
        [0, 1, 0],
        [0, 1, 0],
        [0, 1, 0],
        [1, 0, 0]])

1.3.14 Создать тензор `arr` из 20 случайных целых чисел от 0 до 100. Найти самое частое значение в тензоре. 
Найти индексы в тензоре, соответствующие самому частому значению. Проверить, как работет алгоритм при двух значениях, имеющих наибольшую встречаемость, предложить приемлемое поведение алгоритма для этого случая.

In [158]:
arr = torch.randint(0, 100, (20, ))
arr

tensor([92, 62, 93, 83, 19, 88,  8,  0, 99, 78, 95, 19, 94, 78, 60, 15, 13, 57,
        95, 87])

In [159]:
bc = torch.bincount(arr)
bc

tensor([1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 2,
        0, 0, 0, 1])

In [160]:
ind = torch.where(bc == bc.max(0)[0])[0]
ind

tensor([19, 78, 95])

In [161]:
torch.isin(arr, ind)

tensor([False, False, False, False,  True, False, False, False, False,  True,
         True,  True, False,  True, False, False, False, False,  True, False])

In [162]:
print("Индексы: ", torch.where(torch.isin(arr, ind))[0].tolist())

Индексы:  [4, 9, 10, 11, 13, 18]


## 1.4 Математические задачи

In [150]:
x = torch.arange(11)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [151]:
x = x*torch.sin(x)
x

tensor([ 0.0000,  0.8415,  1.8186,  0.4234, -3.0272, -4.7946, -1.6765,  4.5989,
         7.9149,  3.7091, -5.4402])

1.4.1 Приблизительно (с погрешностью порядка 1%) рассчитать на какой части интервала от 0 до 10 значение функции x * sin(x) больше 0.5.

In [152]:
numbers = torch.arange(2, 101)
numbers

tensor([  2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,
         16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,
         30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,
         44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,
         58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,
         72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,
         86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99,
        100])

1.4.2 Найти все простые числа в пределах ста. (Для решения предлагается использовать Решето Эратосфена) Использовать не более 1 цикла (желательно).

1.4.3 Найти евклидово расстояние между двумя одномерными тензорами одинаковой размерности, не используя готовые решения из библиотек.

In [153]:
x = torch.randint(0, 101, (20, 3), dtype=float)
x

tensor([[ 89.,  41.,  66.],
        [ 33.,  55.,  69.],
        [ 99.,   5.,  59.],
        [ 39.,  21.,  73.],
        [ 63.,  96.,  90.],
        [ 82.,  58.,  88.],
        [ 70.,  41.,  95.],
        [ 68.,  65.,  55.],
        [  8.,  11.,  99.],
        [ 19.,  60.,  57.],
        [ 65.,  33.,   7.],
        [ 24.,  21.,   8.],
        [ 29.,  52.,  61.],
        [ 41.,  46.,  91.],
        [ 30.,  54., 100.],
        [ 55.,  55.,   8.],
        [ 40., 100.,  24.],
        [ 96.,  91.,  73.],
        [ 28.,  71.,  58.],
        [ 77.,  77.,  82.]], dtype=torch.float64)

In [154]:
x.norm(dim=1, p=2).squeeze(-1)

tensor([118.1440,  94.2072, 115.3560,  85.3874, 145.8938, 133.5365, 124.9240,
        108.9679,  99.9300,  84.9117,  73.2325,  32.8786,  85.2408, 109.9000,
        117.5415,  78.1921, 110.3449, 151.0828,  95.8593, 136.3158],
       dtype=torch.float64)

In [155]:
torch.argsort(x, dim=1)

tensor([[1, 2, 0],
        [0, 1, 2],
        [1, 2, 0],
        [1, 0, 2],
        [0, 2, 1],
        [1, 0, 2],
        [1, 0, 2],
        [2, 1, 0],
        [0, 1, 2],
        [0, 2, 1],
        [2, 1, 0],
        [2, 1, 0],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [2, 0, 1],
        [2, 0, 1],
        [2, 1, 0],
        [0, 2, 1],
        [0, 1, 2]])

1.4.4 Создать двумерный тензор 20 на 3, содержащий случайные целые числа от 0 до 100. 
Интерпретируя тензор как 20 векторов из 3х компонент, отсортировать его по длине векторов.

1.4.5 Найти "локальные максимумы" в одномерном тензоре (т.е. значения, большие предыдущего и последующего) `torch.tensor([1, 3, 7, 1, 2, 6, 0, 1])` и вывести их индексы.

1.4.6 Задан произвольный массив numpy (например массив из 100 случайных числе от 0 до 1). Необходимо найти в нем число наиболее близкое к заданному.

1.4.7 Решить матричное уравнение `A*X*B=-C` - найти матрицу X. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

1.4.8 Проверить, является ли система векторов a1 = (3; −3; 0; 7),
a2 = (2; 2; 4; 7), a3 = (1; 2; 3; 4), a4 = (5; −4; 1; 3) линейно зависимой?

1.4.9 Сгенирировать тензор из 200 случайных целых чисел, нормально распрделенных cо стандартным отклонением $\sigma = 10$ и матожиданием $\mu = 0$. Построить тензор гистограммы с 20 бинами. 